/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadoRouteImport } from './routes/resultado'
import { Route as RealistaRouteImport } from './routes/realista'
import { Route as CroquiRouteImport } from './routes/croqui'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadSessionIdRouteImport } from './routes/upload.$sessionId'

const ResultadoRoute = ResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const RealistaRoute = RealistaRouteImport.update({
  id: '/realista',
  path: '/realista',
  getParentRoute: () => rootRouteImport,
} as any)
const CroquiRoute = CroquiRouteImport.update({
  id: '/croqui',
  path: '/croqui',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadSessionIdRoute = UploadSessionIdRouteImport.update({
  id: '/upload/$sessionId',
  path: '/upload/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/croqui': typeof CroquiRoute
  '/realista': typeof RealistaRoute
  '/resultado': typeof ResultadoRoute
  '/upload/$sessionId': typeof UploadSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/croqui': typeof CroquiRoute
  '/realista': typeof RealistaRoute
  '/resultado': typeof ResultadoRoute
  '/upload/$sessionId': typeof UploadSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/croqui': typeof CroquiRoute
  '/realista': typeof RealistaRoute
  '/resultado': typeof ResultadoRoute
  '/upload/$sessionId': typeof UploadSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar'
    | '/croqui'
    | '/realista'
    | '/resultado'
    | '/upload/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar'
    | '/croqui'
    | '/realista'
    | '/resultado'
    | '/upload/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/criar'
    | '/croqui'
    | '/realista'
    | '/resultado'
    | '/upload/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarRoute: typeof CriarRoute
  CroquiRoute: typeof CroquiRoute
  RealistaRoute: typeof RealistaRoute
  ResultadoRoute: typeof ResultadoRoute
  UploadSessionIdRoute: typeof UploadSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultado': {
      id: '/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof ResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realista': {
      id: '/realista'
      path: '/realista'
      fullPath: '/realista'
      preLoaderRoute: typeof RealistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/croqui': {
      id: '/croqui'
      path: '/croqui'
      fullPath: '/croqui'
      preLoaderRoute: typeof CroquiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$sessionId': {
      id: '/upload/$sessionId'
      path: '/upload/$sessionId'
      fullPath: '/upload/$sessionId'
      preLoaderRoute: typeof UploadSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarRoute: CriarRoute,
  CroquiRoute: CroquiRoute,
  RealistaRoute: RealistaRoute,
  ResultadoRoute: ResultadoRoute,
  UploadSessionIdRoute: UploadSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
