/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadoRouteImport } from './routes/resultado'
import { Route as RealistaRouteImport } from './routes/realista'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CroquiRouteImport } from './routes/croqui'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as UploadSessionIdRouteImport } from './routes/upload.$sessionId'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as DashboardExecucoesExecutionIdRouteImport } from './routes/dashboard.execucoes.$executionId'

const ResultadoRoute = ResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const RealistaRoute = RealistaRouteImport.update({
  id: '/realista',
  path: '/realista',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CroquiRoute = CroquiRouteImport.update({
  id: '/croqui',
  path: '/croqui',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const UploadSessionIdRoute = UploadSessionIdRouteImport.update({
  id: '/upload/$sessionId',
  path: '/upload/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExecucoesExecutionIdRoute =
  DashboardExecucoesExecutionIdRouteImport.update({
    id: '/execucoes/$executionId',
    path: '/execucoes/$executionId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/croqui': typeof CroquiRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/realista': typeof RealistaRoute
  '/resultado': typeof ResultadoRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/upload/$sessionId': typeof UploadSessionIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/execucoes/$executionId': typeof DashboardExecucoesExecutionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/croqui': typeof CroquiRoute
  '/realista': typeof RealistaRoute
  '/resultado': typeof ResultadoRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/upload/$sessionId': typeof UploadSessionIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/execucoes/$executionId': typeof DashboardExecucoesExecutionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/croqui': typeof CroquiRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/realista': typeof RealistaRoute
  '/resultado': typeof ResultadoRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/upload/$sessionId': typeof UploadSessionIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/execucoes/$executionId': typeof DashboardExecucoesExecutionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar'
    | '/croqui'
    | '/dashboard'
    | '/realista'
    | '/resultado'
    | '/dashboard/login'
    | '/upload/$sessionId'
    | '/dashboard/'
    | '/dashboard/execucoes/$executionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar'
    | '/croqui'
    | '/realista'
    | '/resultado'
    | '/dashboard/login'
    | '/upload/$sessionId'
    | '/dashboard'
    | '/dashboard/execucoes/$executionId'
  id:
    | '__root__'
    | '/'
    | '/criar'
    | '/croqui'
    | '/dashboard'
    | '/realista'
    | '/resultado'
    | '/dashboard/login'
    | '/upload/$sessionId'
    | '/dashboard/'
    | '/dashboard/execucoes/$executionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarRoute: typeof CriarRoute
  CroquiRoute: typeof CroquiRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  RealistaRoute: typeof RealistaRoute
  ResultadoRoute: typeof ResultadoRoute
  UploadSessionIdRoute: typeof UploadSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultado': {
      id: '/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof ResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realista': {
      id: '/realista'
      path: '/realista'
      fullPath: '/realista'
      preLoaderRoute: typeof RealistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/croqui': {
      id: '/croqui'
      path: '/croqui'
      fullPath: '/croqui'
      preLoaderRoute: typeof CroquiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/upload/$sessionId': {
      id: '/upload/$sessionId'
      path: '/upload/$sessionId'
      fullPath: '/upload/$sessionId'
      preLoaderRoute: typeof UploadSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/execucoes/$executionId': {
      id: '/dashboard/execucoes/$executionId'
      path: '/execucoes/$executionId'
      fullPath: '/dashboard/execucoes/$executionId'
      preLoaderRoute: typeof DashboardExecucoesExecutionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardExecucoesExecutionIdRoute: typeof DashboardExecucoesExecutionIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardExecucoesExecutionIdRoute: DashboardExecucoesExecutionIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarRoute: CriarRoute,
  CroquiRoute: CroquiRoute,
  DashboardRoute: DashboardRouteWithChildren,
  RealistaRoute: RealistaRoute,
  ResultadoRoute: ResultadoRoute,
  UploadSessionIdRoute: UploadSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
